version: '3.7'
services:
  db:
    image: mongo:latest
    ports:
     - 27017:27017
  darky:
    hostname: darky
    build: 
      context: ./
    ports:
      - 80:80
    depends_on:
      - db
  torify:
    restart: always
    image: dockage/tor-privoxy:latest
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8118:8118" # Privoxy